--- #YAML:1.0
name:                IPC-Run3
version:             0.039
abstract:            ~
license:             open_source
generated_by:        ExtUtils::MakeMaker version 6.36_01
distribution_type:   module
requires:     
    Test::More:                    0.31
    Time::HiRes:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
